import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="flex justify-center items-center">header</header>
        {children}
        <footer className="flex justify-center items-center ">footer</footer>
      </body>
    </html>
  );
}
